export const metadata = {
  title: 'EFAesthetics',
  description: 'Generated by Next.js',
};

import './globals.css'
import Navbar from './components/Navbar'
import WhatsAppButton from './components/WhatsAppButton'
import Footer from './components/Footer'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
	<Navbar />
        {children}
        <Footer />
	<WhatsAppButton />
      </body>
    </html>
  );
}
